apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: commit

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: rahulkoju/commit-backend:c24badd7d59c40e9ced100f50393d54417f33248

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: commit-config
            - secretRef:
                name: commit-secret

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
