{
 "title": "Commit App",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "All Commit Pods Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"commit\", container!=\"\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Commit Pods CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"commit\", container!=\"\", container!=\"POD\"}[5m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"commit\", container=\"backend\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"commit\", container=\"backend\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(commit_http_requests_total[5m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate % ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(commit_http_requests_total{status=~\"5..\"}[5m])) / sum(rate(commit_http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "commit_db_pool_total_connections",
     "legendFormat": "__auto"
    },
    {
     "expr": "commit_db_pool_acquired_connections",
     "legendFormat": "__auto"
    },
    {
     "expr": "commit_db_pool_idle_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(commit_http_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-flight Requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "commit_http_requests_in_flight", "legendFormat": "__auto" }
   ]
  }
 ]
}