apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-web
  namespace: commit

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend-web

  template:
    metadata:
      labels:
        app: frontend-web

    spec:
      containers:
        - name: frontend-web
          image: rahulkoju/commit-web:c24badd7d59c40e9ced100f50393d54417f33248

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
