name: Commit Cluster Start/Stop

on:
  # schedule:
    # - cron: '15 2 * * *'   # 02:15 UTC = 8:00 AM NPT
    # - cron: '15 18 * * *'  # 18:15 UTC = 12:00 AM NPT (next day)
  workflow_dispatch:
    inputs:
      action:
        description: 'start or stop'
        required: true
        type: choice
        options:
          - start
          - stop

jobs:
  manage-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Determine action
        id: action
        run: |
            echo "cmd=${{ github.event.inputs.action }}" >> "$GITHUB_OUTPUT"
          # if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          #   echo "cmd=${{ github.event.inputs.action }}" >> "$GITHUB_OUTPUT"
          # elif [ "${{ github.event.schedule }}" == "15 2 * * *" ]; then
          #   echo "cmd=start" >> "$GITHUB_OUTPUT"
          # else 
          #   echo "cmd=stop" >> "$GITHUB_OUTPUT"
          # fi

      - name: Start control-plane, then worker
        if: steps.action.outputs.cmd == 'start'
        run: |
          aws ec2 start-instances --instance-ids i-0cd744fff14b909ab
          aws ec2 wait instance-status-ok --instance-ids i-0cd744fff14b909ab
          aws ec2 start-instances --instance-ids i-06ae7097aeced0d8c
      
      - name: Stop worker, then control-plane
        if: steps.action.outputs.cmd == 'stop'
        run: |
          aws ec2 stop-instances --instance-ids i-06ae7097aeced0d8c
          aws ec2 stop-instances --instance-ids i-0cd744fff14b909ab
